<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit95e0c82f5154e886d9f0990c0c5eb893
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PhpParser\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PhpParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/php-parser/lib/PhpParser',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit95e0c82f5154e886d9f0990c0c5eb893::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit95e0c82f5154e886d9f0990c0c5eb893::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
